on:
  workflow_call:
    inputs:
      deploy-url:
        description: 'The maven repository to deploy to'
        required: true
        type: string
    secrets:
      DEPLOY_USERNAME:
        required: true
      DEPLOY_PASSWORD:
        required: true
      PGP_SECRET:
        required: true
      PGP_PASSPHRASE:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
      - name: Publish
        run: ./gradlew publish
        env:
          MAVEN_DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          MAVEN_DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          MAVEN_DEPLOY_URL: ${{ inputs.deploy-url }}
